http:
  port: 8080
  maxHeaderBytes: 1
  readTimeout: 10s
  writeTimeout: 10s

postgres:
  host: localhost
  port: 5432
  database: postgres
  sslMode: disable

jwt:
  accessTokenTTL: 15m
  refreshTokenTTL: 24h
